FROM ubuntu:18.04
# This dockerfile is not part of the CI/CD, but used for local testing of docker containers.
# Updating packages
RUN apt-get update --fix-missing

RUN apt-get -y install git
RUN echo "CLONING REPOSITORY"
RUN git clone https://github.com/DevOps2021-gb/devops2021.git -b develop
RUN echo "INSTALLING MAVEN"
RUN apt install maven -y
WORKDIR "/devops2021/java-itu-minitwit"
RUN echo "BUILDING PROJECT"
# no test are run
RUN mvn -B package -Dmaven.test.skip=true
WORKDIR "/devops2021/java-itu-minitwit/target"

EXPOSE 4567
CMD java -jar java-itu-minitwit-1.0-SNAPSHOT.jar "mysql://db:3306/minitwit?allowPublicKeyRetrieval=true&useSSL=false" "root" "root" "true"
