version: '3.3'

services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: minitwit
        ports:
            - "3306:3306"
        networks:
            - main
    minitwit:
        build:
            context: ./
            dockerfile: Dockerfile-localDB
        container_name: minitwit
        ports:
            - "4567:4567"
        networks:
            - main
        depends_on:
            - db
            - grafana
            - prometheus

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
        - "9090:9090"
        networks:
        - main

    grafana:
        image: grafana/grafana:4.5.2
        container_name: grafana
        volumes:
        - grafana-storage:/var/lib/grafana
        ports:
        - "3000:3000"  
        networks:
        - main
networks:
    main:
        driver: bridge
volumes:
  grafana-storage:
