version: '3.3'

services:
    minitwit:
        image: mertz/minitwit:latest
        container_name: minitwit
        ports:
            - "4567:4567"
        networks:
            - main
        depends_on:
            - grafana
            - prometheus
        restart: always

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
        - "9090:9090"
        networks:
        - main

    grafana:
        image: grafana/grafana:4.5.2
        container_name: grafana
        volumes:
        - grafana-storage:/var/lib/grafana
        ports:
        - "3000:3000"
        networks:
        - main
networks:
    main:
        driver: bridge

volumes:
  grafana-storage:

