FROM python:3.7-alpine

RUN mkdir /minitwit
# Updating packages
apt-get update

# ---------------------------------------
#          MySQL Setup
# ---------------------------------------

# Setting MySQL root user password root/root
 debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
 debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'


# Installing packages
apt-get install -y mysql-server mysql-client

mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'; FLUSH privileges;"
service mysql restart
# create client database
mysql -u root -proot -e "CREATE DATABASE minitwit;"


echo "CLONING REPOSITORY"
git clone https://github.com/JesperFalkenberg/devops2021.git -b feature/deploy
echo "INSTALLING MAVEN"
apt install maven -y
cd devops2021/java-itu-minitwit/
echo "BUILDING PROJECT"
mvn package
cd target

java -jar java-itu-minitwit-1.0-SNAPSHOT.jar

echo "================================================================="
echo "=                            DONE                               ="
echo "================================================================="
echo "Navigate in your browser to:"
THIS_IP=`hostname -I | cut -d" " -f1`
echo "http://${THIS_IP}:4567"
WORKDIR /minitwit

RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python", "minitwit_mysql.py"]
