FROM ubuntu:18.04

# Updating packages
sudo apt-get update

# ---------------------------------------
#          MySQL Setup
# ---------------------------------------

# Setting MySQL root user password root/root
 debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
 debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'


# Installing packages
sudo apt-get install -y mysql-server mysql-client

sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'; FLUSH privileges;"
sudo service mysql restart
# create client database
sudo mysql -u root -proot -e "CREATE DATABASE minitwit;"


echo "CLONING REPOSITORY"
sudo git clone https://github.com/JesperFalkenberg/devops2021.git -b feature/deploy
echo "INSTALLING MAVEN"
sudo apt install maven -y
cd devops2021/java-itu-minitwit/
echo "BUILDING PROJECT"
sudo mvn package
cd target

sudo java -jar java-itu-minitwit-1.0-SNAPSHOT.jar

echo "================================================================="
echo "=                            DONE                               ="
echo "================================================================="
echo "Navigate in your browser to:"
THIS_IP=`hostname -I | cut -d" " -f1`
echo "http://${THIS_IP}:4567"

EXPOSE 4567
