version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/java_minitwit
    container_name: minitwit
    networks:
      - main
    ports:
        - '4567:4567'