version: '3.3'

services:
    minitwit:
        image: mertz/minitwit:latest
        ports:
            - "4567:4567"
        networks:
            - main
        depends_on:
            - grafana
            - prometheus
        restart: always

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - "9090:9090"
        networks:
        - main

    grafana:
        image: grafana/grafana:4.5.2
        volumes:
        - grafana-storage:/var/lib/grafana
        ports:
        - "3000:3000"  
        networks:
        - main
networks:
    main:
        driver: bridge
        
volumes:
  grafana-storage:

