version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/java_minitwit
    container_name: minitwit
    networks:
      - main
    depends_on:
      - mysqlimage
    ports:
        - '4567:4567'
        
  mysqlimage:
    image: ${DOCKER_USERNAME}/minitwit_mysqlimage
    container_name: minitwit_mysql
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root