name: Staging deployment

on:
  push:
    branches: [ deploy/actions ]

jobs: 
  build:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_SIF }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_SIF }}
          repository: psiphph/minitwit
        
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_SIF }}
         
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "minitwit" --image docker-18-04 --size s-1vcpu-1gb --region fra1 --wait
