name: Staging deployment

on:
  push:
    branches: [ main ]

jobs: 
  build:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mertz/minitwit:latest
          # DB connection string and credentials for Dockerfile
          build-args: |
            DB_CONN_STRING=${{ secrets.DB_CONNECTION_STRING }} 
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_TEST_CONN_STRING=${{ secrets.DB_TEST_CONNECTION_STRING }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Minitwit API and GUI
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server we wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # user of the server we want to ssh into
          script: |
            wget https://raw.githubusercontent.com/DevOps2021-gb/devops2021/main/bootstrap.sh
            sh bootstrap.sh

  pre-release:
    #https://github.com/marketplace/actions/automatic-releases
    needs: deploy
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          
  deploy-backup:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Minitwit API and GUI
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_BACKUP}} # IP address of backup server
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # user of the server we want to ssh into
          script: |
            wget https://raw.githubusercontent.com/DevOps2021-gb/devops2021/main/bootstrap.sh
            ./bootstrap.sh
